server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/interview?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
